PROFILE_TYPE_VENDOR = "vendor"
PROFILE_TYPE_CUSTOMER = 'customer'
PROFILE_TYPE_ADMIN = 'admin'

PROFILE_TYPE = (
    (PROFILE_TYPE_VENDOR, "vendor"),
    (PROFILE_TYPE_CUSTOMER, "customer"),
    (PROFILE_TYPE_ADMIN, "admin")
)

PRODUCT_TYPE_PRODUCT = "product"
PRODUCT_TYPE_SERVICE = 'service'

PRODUCT_TYPES = (
    (PRODUCT_TYPE_PRODUCT, "Product"),
    (PRODUCT_TYPE_SERVICE, "Service")
)

ORDER_STATUS_COMPLETED = "completed"
ORDER_STATUS_UPCOMING = 'upcoming'
ORDER_STATUS_CANCELLED = 'cancelled'

ORDER_STATUS = (
    (ORDER_STATUS_COMPLETED, "Completed"),
    (ORDER_STATUS_UPCOMING, "Upcoming"),
    (ORDER_STATUS_CANCELLED, "Cancelled")
)