# Generated by Django 3.0.5 on 2021-03-24 10:21

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profileType', models.CharField(choices=[('vendor', 'vendor'), ('customer', 'customer'), ('admin', 'admin')], default='customer', max_length=1024)),
                ('vendorDescription', models.TextField(null=True)),
                ('contact', djongo.models.fields.JSONField()),
                ('address', djongo.models.fields.JSONField()),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=10)),
                ('image', models.TextField()),
                ('lastAppActivity', models.DateTimeField(null=True)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_admin_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'profiles',
                'managed': False,
            },
        ),
    ]
